// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "getting-started.mdx": () => import("../content/docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "workspace-strategy.mdx": () => import("../content/docs/workspace-strategy.mdx?collection=docs"), "examples/docker-cluster.mdx": () => import("../content/docs/examples/docker-cluster.mdx?collection=docs"), "examples/index.mdx": () => import("../content/docs/examples/index.mdx?collection=docs"), "examples/server-bootstrap.mdx": () => import("../content/docs/examples/server-bootstrap.mdx?collection=docs"), "packages/auth.mdx": () => import("../content/docs/packages/auth.mdx?collection=docs"), "packages/authorized-keys.mdx": () => import("../content/docs/packages/authorized-keys.mdx?collection=docs"), "packages/aws.mdx": () => import("../content/docs/packages/aws.mdx?collection=docs"), "packages/builder.mdx": () => import("../content/docs/packages/builder.mdx?collection=docs"), "packages/cli.mdx": () => import("../content/docs/packages/cli.mdx?collection=docs"), "packages/cluster.mdx": () => import("../content/docs/packages/cluster.mdx?collection=docs"), "packages/docker.mdx": () => import("../content/docs/packages/docker.mdx?collection=docs"), "packages/endpoint.mdx": () => import("../content/docs/packages/endpoint.mdx?collection=docs"), "packages/env.mdx": () => import("../content/docs/packages/env.mdx?collection=docs"), "packages/firewall.mdx": () => import("../content/docs/packages/firewall.mdx?collection=docs"), "packages/fs.mdx": () => import("../content/docs/packages/fs.mdx?collection=docs"), "packages/groups.mdx": () => import("../content/docs/packages/groups.mdx?collection=docs"), "packages/index.mdx": () => import("../content/docs/packages/index.mdx?collection=docs"), "packages/nodevisor.mdx": () => import("../content/docs/packages/nodevisor.mdx?collection=docs"), "packages/os.mdx": () => import("../content/docs/packages/os.mdx?collection=docs"), "packages/packages.mdx": () => import("../content/docs/packages/packages.mdx?collection=docs"), "packages/pwsh.mdx": () => import("../content/docs/packages/pwsh.mdx?collection=docs"), "packages/registry.mdx": () => import("../content/docs/packages/registry.mdx?collection=docs"), "packages/schema.mdx": () => import("../content/docs/packages/schema.mdx?collection=docs"), "packages/services.mdx": () => import("../content/docs/packages/services.mdx?collection=docs"), "packages/shell.mdx": () => import("../content/docs/packages/shell.mdx?collection=docs"), "packages/ssh.mdx": () => import("../content/docs/packages/ssh.mdx?collection=docs"), "packages/ufw.mdx": () => import("../content/docs/packages/ufw.mdx?collection=docs"), "packages/users.mdx": () => import("../content/docs/packages/users.mdx?collection=docs"), }),
};
export default browserCollections;