name: Nodevisor Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # , centos:7, fedora:latest
        os: ["debian:buster", "ubuntu:latest"]
        node-version: [16.x, 18.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker for each OS in the matrix
      - name: Set up Docker container for ${{ matrix.os }}
        run: |
          docker run -v ${{ github.workspace }}:/workspace \
                     -w /workspace \
                     ${{ matrix.os }} \
                     /bin/bash -c "
                       # Update and install essential packages
                       if [ '${{ matrix.os }}' = 'debian:buster' ]; then
                         apt-get update && apt-get install -y build-essential curl;
                       elif [ '${{ matrix.os }}' = 'ubuntu:latest' ]; then
                         apt-get update && apt-get install -y build-essential curl;
                       elif [ '${{ matrix.os }}' = 'centos:7' ]; then
                         yum update -y && yum groupinstall -y 'Development Tools' && yum install -y curl;
                       elif [ '${{ matrix.os }}' = 'fedora:latest' ]; then
                         dnf update -y && dnf groupinstall -y 'Development Tools' && dnf install -y curl;
                       fi;

                       # Install Node.js
                       curl -fsSL https://deb.nodesource.com/setup_${{ matrix.node-version }} | bash -
                       if [ '${{ matrix.os }}' = 'debian:buster' ] || [ '${{ matrix.os }}' = 'ubuntu:latest' ]; then
                         apt-get install -y nodejs;
                       elif [ '${{ matrix.os }}' = 'centos:7' ]; then
                         yum install -y nodejs;
                       elif [ '${{ matrix.os }}' = 'fedora:latest' ]; then
                         dnf install -y nodejs;
                       fi;

                       # Step 3: Install project dependencies
                       npm install;

                       # Step 4: Run tests
                       npm test;
                     "